apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myapp-secret
                key: password
        volumeMounts:
          - name: config-vol
            mountPath: /etc/config
        volumeDevices: []
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
          - containerPort: 80
      volumes:
      - name: config-vol
        configMap:
          name: myconfig
