apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend6
  template:
    metadata:
      labels:
        app: backend6
    spec:
      serviceAccountName: default
      containers:
      - name: backend
        image: bitnami/kubectl:latest
        command: ["sh", "-c"]
        args:
          - while true; do echo "Checking secrets..."; kubectl get secrets; sleep 10; done
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
