apiVersion: batch/v1
kind: CronJob
metadata:
  name: myapp-cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-container
            image: bitnami/kubectl:latest
            args:
              - "get"
              - "pods"
            env:
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: myapp-secret
                    key: password
          restartPolicy: Never
