apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hashicorp/http-echo:0.2.3
        env:
          - name: WELCOME_MSG
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                key: user_key
        args:
          - "-listen=:80"
          - "-text=$(WELCOME_MSG)"
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
